services:
  api:
    container_name: api
    build:  
      context: .
      dockerfile: ./Dockerfile
    env_file:
    - .env
    restart: unless-stopped
    volumes:
      - .:/api/
      - /api/node_modules
    ports:
      - ${PORT}:${PORT}
    environment:
      - PORT=${PORT}
    depends_on:
      - postgres
    networks:
      - app-network
  postgres:
    container_name: postgres
    build: 
      context: .
      dockerfile: ./database/Dockerfile
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - ${DB_PORT}:${DB_PORT}
    volumes:
      - docker-nest-postgres:/var/lib/postgresql/data
    networks:
      - app-network

volumes:
  docker-nest-postgres:
networks:
    app-network:
        driver: bridge 
